name: Build and Release APK

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version name for manual build (e.g., 1.0.0)'
        required: false
        default: '1.0.0'

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Get version name
        id: version
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            VERSION=${GITHUB_REF#refs/tags/}
          else
            VERSION="v${{ github.event.inputs.version }}"
          fi
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "VERSION_NAME=${VERSION#v}" >> $GITHUB_OUTPUT
          
      - name: Update version in build.gradle
        run: |
          VERSION_NAME="${{ steps.version.outputs.VERSION_NAME }}"
          VERSION_CODE=$(date +%Y%m%d%H)
          sed -i "s/versionCode .*/versionCode $VERSION_CODE/" app/build.gradle
          sed -i "s/versionName .*/versionName \"$VERSION_NAME\"/" app/build.gradle
      
      - name: Build Debug APK
        run: ./gradlew assembleDebug
        
      - name: Build Release APK
        run: ./gradlew assembleRelease
      
      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
          
      - name: Upload Release APK
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: app/build/outputs/apk/release/app-release-unsigned.apk
      
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: Ayo Chat ${{ steps.version.outputs.VERSION }}
          body: |
            ## Ayo Chat ${{ steps.version.outputs.VERSION }}
            
            ### Features
            - Real-time messaging
            - Multiple chat rooms
            - Device-based authentication
            - Message deletion (within 5 minutes)
            - Typing indicators
            - Country flags based on IP
            - Offensive word filtering
            - Private and public rooms
            
            ### Installation
            1. Download the APK file below
            2. Enable "Install from Unknown Sources" in your Android settings
            3. Install the APK
            4. Open Ayo Chat and start chatting!
            
            ### Requirements
            - Android 5.0 (API 21) or higher
            - Internet connection
            
            ### Server
            Connected to: https://api.naderr.link
          files: |
            app/build/outputs/apk/debug/app-debug.apk
            app/build/outputs/apk/release/app-release-unsigned.apk
          token: ${{ secrets.GITHUB_TOKEN }}
          generate_release_notes: true
          draft: false
          prerelease: false
